name: "dali"
backend: "dali"
max_batch_size: 0
input [
  {
    name: "DALI_INPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]

output [
  {
    name: "DALI_OUTPUT_0"
    data_type: TYPE_UINT8
    dims: [ -1, -1, 3 ]
  }
]
